In [1]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


In [3]:
# TENSOR - Way to represent data ==========> use torch.tensor to create a tensor

#scalar
scalar = torch.tensor(4)
print(f"tensor : {scalar}")
print(f"Dimensions of tensor : {scalar.ndim}")
print(scalar.item()) # To get tensor as a python int

tensor : 4
Dimensions of tensor : 0
4


In [4]:
# Vector
vector = torch.tensor([7,7])
print(f"vector : {vector}")


vector : tensor([7, 7])


In [5]:
vector.shape

torch.Size([2])

In [6]:
# Matrix
MATRIX = torch.tensor([[2,4], [3,5]])
MATRIX

tensor([[2, 4],
        [3, 5]])

In [7]:
MATRIX.ndim

2

In [8]:
MATRIX[1]

tensor([3, 5])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

In [13]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
# Random tensor
random = torch.rand(4, 3)
random

tensor([[0.2816, 0.5339, 0.4203],
        [0.6162, 0.3706, 0.2654],
        [0.0049, 0.8218, 0.8662],
        [0.8770, 0.0240, 0.5054]])

In [15]:
random.shape

torch.Size([4, 3])

In [16]:
random.ndim

2

In [17]:
# Create tensor with same shape as a image
random_image = torch.rand(size=(224, 224, 3)) # height, width, color channels RGB
random_image.shape, random_image.ndim

(torch.Size([224, 224, 3]), 3)

In [18]:
# 0 tensor
zero = torch.zeros(4,3)

In [19]:
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [20]:
zero*random

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
ones = torch.ones(3,4)

In [22]:
ones.dtype # Default is 32 float

torch.float32

In [23]:
# Range of tensors
torch.range(1, 19)

<ipython-input-23-3af217382e2f>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1, 19)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19.])

In [24]:
torch.arange(1, 19)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [25]:
ranging = torch.arange(0, 1000, 55)

In [26]:
ranging

tensor([  0,  55, 110, 165, 220, 275, 330, 385, 440, 495, 550, 605, 660, 715,
        770, 825, 880, 935, 990])

In [27]:
# Tensors like
zero_ranging = torch.zeros_like(ranging)

In [28]:
zero_ranging

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
# float tensor
f = torch.rand(size=(3,1), dtype=torch.float16)
print(f.dtype)
r = torch.rand(size=(3,1), dtype = None) # even if none, the default type is float32
r.dtype

torch.float16


torch.float32

In [30]:
explore = torch.rand(size=(2,3),
                     dtype = None,
                     device = None, #cuda for gpu, cpu as default
                     requires_grad=False # calculate graqdient during operation
                     )

In [31]:
f16 = explore.type(torch.float16)

In [32]:
f16.dtype

torch.float16

In [33]:
## implicit conversion occurs between floats, doubles, ints, longs

In [34]:
# tensor.dtype = data type
# tensor.device = device the tensor is running on
# tensor.shape (attribute) / tensor.size() (functions)= shape

In [35]:
f16.shape, f16.size(), f16.dtype, f16.device

(torch.Size([2, 3]), torch.Size([2, 3]), torch.float16, device(type='cpu'))

In [36]:
f13 = f16.to('cpu')

# Tensor operations
"""
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

"""

In [37]:
tensor = torch.rand(3)

In [38]:
tensor

tensor([0.5097, 0.9938, 0.3918])

In [39]:
tensor + 10

tensor([10.5097, 10.9938, 10.3918])

In [40]:
tensor * 10

tensor([5.0975, 9.9384, 3.9181])

In [41]:
tensor - 10

tensor([-9.4903, -9.0062, -9.6082])

In [42]:
torch.mul(tensor, 10)

tensor([5.0975, 9.9384, 3.9181])

In [43]:
torch.add(tensor, 25)

tensor([25.5097, 25.9938, 25.3918])

In [44]:
tensor * tensor

tensor([0.2598, 0.9877, 0.1535])

In [45]:
torch.matmul(tensor, tensor) # Automatically took the Transpose of the tensor before multiplying it

tensor(1.4011)

In [46]:
tensor @ tensor # matrix multiplication

tensor(1.4011)

In [47]:
A = torch.arange(1,7).reshape(3,2)
A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [48]:
B = torch.arange(7, 13).reshape(3,2).T
B

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [49]:
torch.mm(A,B) == torch.matmul(A,B)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

Finding data analysis on tensor

In [50]:
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [51]:
x.max(), torch.max(x)

(tensor(91), tensor(91))

In [52]:
x.min(), torch.min(x)

(tensor(1), tensor(1))

In [53]:
x.type(torch.float32).mean(), torch.mean(x.type(torch.float32)) #By default is int64, but need float or double to perform mean calculations

(tensor(46.), tensor(46.))

In [54]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [55]:
torch.argmax(x), x.argmax() #returns the index with max value

(tensor(9), tensor(9))

In [56]:
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

## Stacking, squeezing and unsqueesing

View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor

Squeeze - removes all `1` dimensions from a tensor
Unsqueeze - add a `1` dimension to a target tensor
Permute - Return a view of the input with dimensions permuted (swapped)

In [57]:
x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [58]:
x.reshape(1,9) # 2D array # Must be compatable with the the total number of elements

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [59]:
z = x.view(1,9) # x and z share the same memory space, change in one changes both, z added another bracket. now is a 2d vector
z

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [60]:
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [61]:
torch.stack([x, x, x], dim= 0)

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [62]:
torch.stack([x, x, x], dim=1)

tensor([[5, 5, 5],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]])

In [63]:
torch.unsqueeze(x, dim=0)

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [64]:
# squeese - Removed on square bracket, all the single dimensions
z, z.squeeze(), z.shape, z.squeeze().shape

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]),
 tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]),
 torch.Size([1, 9]),
 torch.Size([9]))

##If the dimensions are : 1, 3, 1
##After squeeze: 3 - It will remove every dimension where the value of it is 1

#Unsqueeze

### Dim= 0 adds 1 dimensions before existing dimension {1 in the front}
### Dim=1 adds 1 dimension after the existing

In [65]:
z = z.squeeze()

print(f"Old tensor: {z}")
print(f"Old shape: {z.shape}")
print()

print(f"New tensor: {z.unsqueeze(dim=0)}")
print(f"New shape: {z.unsqueeze(dim=0).shape}")
print()

print(f"Newer tensor: {z.unsqueeze(dim=1)}")
print(f"Newer shape: {z.unsqueeze(dim=1).shape}")

Old tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Old shape: torch.Size([9])

New tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])

Newer tensor: tensor([[5],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
Newer shape: torch.Size([9, 1])


#Permute

## The permuted image and the image share same space. Same as view

In [66]:
image = torch.rand(size=(224,224,3)) # height, width, color

permuted = image.permute(2, 0, 1) # Shift the 2nd dimension(3) to the first position (224)
permuted.shape # color, height, width

torch.Size([3, 224, 224])

In [67]:
image[0, 0, 0] = 2323
image [0, 0, 0], permuted[0, 0, 0]

(tensor(2323.), tensor(2323.))

#Indexing

In [68]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [69]:
x [0], x [0 , 1], x [0, 0, 0] # 0 - returns everything inside first bracket, 0,1: gives everything in the bracket and the 1st row

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([4, 5, 6]),
 tensor(1))

In [70]:
x [:, :, 1] #From all the elements, from all the rows, give me 2nd column

tensor([[2, 5, 8]])

In [71]:
x [:, 1, 1], x [0, 1, 1] # As seen the : gives you a list and whatever elemnets are inside it

(tensor([5]), tensor(5))

In [72]:
x [0, 0, :]

tensor([1, 2, 3])

In [73]:
x [:, :, 2]

tensor([[3, 6, 9]])

#Pytorch -> numpy = torch.Tensor.numpy()

#Numpy array -> Pytorch tensor = torch.from_numpy(ndarray)
Automatically casted to suit the data type of the numpy

In [77]:
import numpy as np

array = np.arange(1, 10)
array, array.dtype

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int64'))

In [78]:
tensor = torch.from_numpy(array)
tensor, tensor.dtype

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)

In [81]:
array = array - 1
array , tensor # No change to the tensor, it is a separate copy

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [82]:
tensor = torch.ones(7)
tensor

tensor([1., 1., 1., 1., 1., 1., 1.])

In [84]:
array = tensor.numpy()
array # Array will now have the data type of the tensor it is converted from

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

# Reproducibility

In [89]:
RANDOM = 23

torch.manual_seed(RANDOM) # This line has to be present before each random one we need to be reproduceable. Or else they will result in different numbers
A = torch.rand(3,4)
torch.manual_seed(RANDOM)
B = torch.rand(3, 4)
A , B

(tensor([[0.4283, 0.2889, 0.4224, 0.3571],
         [0.9577, 0.1100, 0.2933, 0.9205],
         [0.5876, 0.1299, 0.6729, 0.1028]]),
 tensor([[0.4283, 0.2889, 0.4224, 0.3571],
         [0.9577, 0.1100, 0.2933, 0.9205],
         [0.5876, 0.1299, 0.6729, 0.1028]]))

In [98]:
RANDOM = 33
torch.manual_seed(RANDOM)

In [99]:
C = torch.rand(4,4)
torch.manual_seed(RANDOM)
D = torch.rand(4, 4)
C, D

(tensor([[0.6186, 0.5587, 0.1937, 0.3360],
         [0.2008, 0.6970, 0.6367, 0.1452],
         [0.8213, 0.2365, 0.3702, 0.9168],
         [0.0333, 0.7183, 0.0325, 0.2320]]),
 tensor([[0.6186, 0.5587, 0.1937, 0.3360],
         [0.2008, 0.6970, 0.6367, 0.1452],
         [0.8213, 0.2365, 0.3702, 0.9168],
         [0.0333, 0.7183, 0.0325, 0.2320]]))

#Using GPU for Pytorch computations

## Google collab , GPU, cloud computing

In [2]:
!nvidia-smi

Fri May 31 12:26:59 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [4]:
# torch check for GPU
import torch
torch.cuda.is_available()

True

In [5]:
# Device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [6]:
torch.cuda.device_count()

1

#Hosting Tensors on GPU

In [7]:
tensor = torch.tensor([1, 2, 3], device='cpu')
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [8]:
tensor_gpu = tensor.to(device)

In [15]:
tensor_gpu #cuda : 0 means that we are using the first gpu (the only one available in this case)


tensor([1, 2, 3], device='cuda:0')

In [11]:
tensor_cpu = tensor.to('cpu')
tensor_cpu.numpy()

array([1, 2, 3])

In [13]:
tensor_cpu = tensor.cpu().numpy()
tensor_cpu

array([1, 2, 3])