## Introduction to Tensor

- Scalar: 0 dim
- Vecotr: 1 dim
- Matrix: 2 dim
- Tensor: <= 3 dim

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.19.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions on a tensor
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of our vector
vector.ndim

1

In [ ]:
# Create a matrix
matrix = tf.constant([[10, 8],
                      [10, 7]])
matrix, matrix.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  8],
        [10,  7]], dtype=int32)>,
 2)

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10., 4.],
                              [3., 1.],
                              [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  4.],
       [ 3.,  1.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Tensor
tensor = tf.constant([[[1,2,3], [2,3,4]], [[3,4,5], [3, 4, 5]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 3, 4]],

       [[3, 4, 5],
        [3, 4, 5]]], dtype=int32)>

In [ ]:
tensor.ndim

3

### Creaing tensors with `tf.Variable`

In [ ]:
changeable_tensor = tf.Variable([10, 8])
unchangeable_tensor = tf.constant([10, 3])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  8], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  3], dtype=int32)>)

In [ ]:
# Assign
changeable_tensor[0].assign(8)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([8, 8], dtype=int32)>

### Creating random tensors

Random tensors are tensors of some tensor of selected size

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [ ]:
not_shuffled = tf.constant([[10, 3], [2, 3], [3, 4]])
not_shuffled.ndim

2

In [ ]:
# Shuffle tnesor - Along the first dimsion
tf.random.set_seed(42) # Global level seed
tf.random.shuffle(not_shuffled, seed=42) # Operational level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  3],
       [ 2,  3],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.ones([10, 8])

<tf.Tensor: shape=(10, 8), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(4, 5))

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### Numpy to Tensorflow

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU

In [ ]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getiing informaiton form tensors
- Shape: len of each dimemntion
- Rank: num of dimemensions
- Axis: Particular dimention of tensor
- Size: Total number of items in a tensor

In [ ]:
# Create a rank 4 tensor
rank_4_tensor = tf.zeros((2,3,4,5)) # last dim -> first dim

In [ ]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
# Get various attributes of our tensor
print('Datatypes of every element:', rank_4_tensor.dtype)
print('Number of dimension(rank): ', rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print('Total numbher of elements in the tensor: ', tf.size(rank_4_tensor).numpy())

Datatypes of every element: <dtype: 'float32'>
Number of dimension(rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total numbher of elements in the tensor:  120


In [ ]:
rank_2_tensor = tf.ones((2, 4))
rank_2_tensor

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # For every axis before the last one
rank_3_tensor

<tf.Tensor: shape=(2, 4, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]]], dtype=float32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=-1) # Expand on which dimension

<tf.Tensor: shape=(2, 4, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]]], dtype=float32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0) # Expand on which dimension

<tf.Tensor: shape=(1, 2, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

**Matrix multiplicaiton**

In [ ]:
r2_tensor = tf.ones((4,2))
tf.matmul(rank_2_tensor, r2_tensor)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

### Changing the datatype of a tensor

In [ ]:
B = tf.constant([1.3, 4.5])
B.dtype

tf.float32

In [ ]:
C = tf.constant([4, 5])
C.dtype

tf.int32

In [ ]:
D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.3, 4.5], dtype=float16)>

**Aggregating tensors**

Condensing them from multiple values down to a smaller amount of values

- Min
- Man
- Mean
- Sume
- Abosolute

In [ ]:
# Get the absolute values
D = tf.constant([-5, -3])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 3], dtype=int32)>

In [ ]:
E = tf.constant(np.random.randint(0, 100, 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([52, 12, 85,  9,  4, 44,  5, 37, 27, 84,  0, 40, 20, 67, 17, 41,  2,
        9, 75, 62, 30,  4, 44, 14, 39, 69, 39, 17, 60, 86, 81, 95, 97, 12,
       71,  4, 11, 35, 27, 80, 95, 85, 74, 15, 79, 13, 40, 56, 54, 34])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [ ]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2152>

In [ ]:
tf.reduce_mean(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=43.03125>

In [ ]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=893.0>

In [ ]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=29.890625>

In [ ]:
tf.math.argmax(E)

<tf.Tensor: shape=(), dtype=int64, numpy=32>

In [ ]:
tf.math.argmin(E)

<tf.Tensor: shape=(), dtype=int64, numpy=10>

### Squeesing a tensor

In [ ]:
# Create a tensor
G = tf.constant(tf.random.uniform(shape=[50]), shape=[1,1,1,1,50])

In [ ]:
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [ ]:
G_squeeze = tf.squeeze(G)
G_squeeze.shape

TensorShape([50])

### One-hot encoding tesnors

In [ ]:
# Create a list of indicies
some_list = [0,1,2,3,1] # red, green, blue, yellow

tf.one_hot(indices=some_list, depth=len(some_list))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.]], dtype=float32)>

In [ ]:
# Speify custom values for one hot encoding
tf.one_hot(some_list, len(some_list), on_value='This', off_value='Nah')

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'This', b'Nah', b'Nah', b'Nah', b'Nah'],
       [b'Nah', b'This', b'Nah', b'Nah', b'Nah'],
       [b'Nah', b'Nah', b'This', b'Nah', b'Nah'],
       [b'Nah', b'Nah', b'Nah', b'This', b'Nah'],
       [b'Nah', b'This', b'Nah', b'Nah', b'Nah']], dtype=object)>

### Squaring, log, square root

In [ ]:
# Create a new tensor
H = tf.cast(tf.range(1,10), dtype=tf.float16)
H = tf.square(H)

In [ ]:
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float16, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float16)>

In [ ]:
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.   , 1.387, 2.197, 2.773, 3.219, 3.584, 3.893, 4.16 , 4.395],
      dtype=float16)>

### Tensors and Numpy

Tensorflow and Numpy interaction

In [ ]:
J = tf.constant(np.array([2,3,4,5]))
J

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([2, 3, 4, 5])>

In [ ]:
np.array(J)

array([2, 3, 4, 5])

In [ ]:
# Convert tensor to Numpy
type(J.numpy())

numpy.ndarray

In [ ]:
# Default types of numpy diff from tf
J = tf.constant([2.,3.,4.,5.])
numpy_J = tf.constant(np.array([2.,3.,4.,5.]))
J.dtype, numpy_J.dtype

(tf.float32, tf.float64)

## Devices

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

## Test

In [ ]:
# scalar
s = tf.constant(2)
s.ndim
v = tf.constant([1,1])
m = tf.constant([[2,3], [3,5]])
t = tf.constant(tf.ones(shape=(1,3,4)))
s.ndim, v.ndim, m.ndim, t.ndim

(0, 1, 2, 3)

In [ ]:
random_1 = tf.random.uniform(shape=(5,300), minval=0, maxval=1)
random_2 = tf.random.uniform(shape=(5,300), minval=0, maxval=1)

In [ ]:
random_1 * random_2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.50998044, 0.30451736, 0.01618501, ..., 0.3357493 , 0.0698769 ,
        0.23107657],
       [0.0296768 , 0.05186556, 0.51247376, ..., 0.4033517 , 0.10968234,
        0.14504547],
       [0.00674238, 0.17331377, 0.11139643, ..., 0.15974203, 0.31482717,
        0.9880052 ],
       [0.01282308, 0.06803418, 0.04070826, ..., 0.51570535, 0.01522908,
        0.14413354],
       [0.3336517 , 0.18272708, 0.91464335, ..., 0.2465836 , 0.09393981,
        0.05832076]], dtype=float32)>

In [ ]:
random_1 @ tf.reshape(random_2, shape=(300, 5))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.742355, 78.96602 , 76.4375  , 79.90297 , 79.41224 ],
       [73.00635 , 70.02399 , 70.02371 , 72.228424, 70.10681 ],
       [78.79178 , 78.55488 , 75.45839 , 77.58642 , 74.71056 ],
       [75.785736, 74.37854 , 71.91179 , 73.319595, 71.63659 ],
       [84.2247  , 77.5869  , 79.07501 , 81.65291 , 77.13225 ]],
      dtype=float32)>

In [ ]:
random_3 = tf.random.uniform(shape=(224,224,3), maxval=1, minval=0)
tf.reduce_max(random_3, axis=1), tf.reduce_min(random_3, axis=1)

(<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
 array([[0.9873078 , 0.99753857, 0.9999181 ],
        [0.9956944 , 0.9998206 , 0.9929837 ],
        [0.9936291 , 0.9918921 , 0.9598745 ],
        [0.9954462 , 0.9990394 , 0.99100053],
        [0.99979174, 0.99845314, 0.99972796],
        [0.99763167, 0.9913243 , 0.9981377 ],
        [0.99651706, 0.9953166 , 0.9971727 ],
        [0.9962779 , 0.99512875, 0.9846082 ],
        [0.9994384 , 0.99306   , 0.9920795 ],
        [0.9831891 , 0.9939563 , 0.99853885],
        [0.99338603, 0.99928355, 0.99429536],
        [0.9894918 , 0.9972334 , 0.99655294],
        [0.9867376 , 0.99908555, 0.99209356],
        [0.9985775 , 0.9989476 , 0.99646795],
        [0.9961543 , 0.9943174 , 0.9998902 ],
        [0.99391735, 0.9979564 , 0.9997649 ],
        [0.9933237 , 0.9972919 , 0.99926424],
        [0.99841547, 0.99855506, 0.9927906 ],
        [0.9926841 , 0.9860084 , 0.9954239 ],
        [0.99876   , 0.9978906 , 0.98749316],
        [0.99708664, 0.998627

In [ ]:
rand_3 = tf.random.uniform(shape=(1,224,224,3))
tf.squeeze(rand_3).shape

TensorShape([224, 224, 3])

In [ ]:
rand_4 = tf.constant(np.arange(1,11))
tf.math.argmax(rand_4), tf.math.argmin(rand_4)
rand_4

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])>

In [ ]:
tensor_4 = tf.one_hot(indices=rand_4, depth=len(rand_4))
tensor_4

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>